name: CI

on:
  workflow_dispatch:   # Permite ejecutar manualmente desde Actions -> Run workflow
  push:
    branches: [ main, develop, "feature/**" ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Show workspace & repo files
        run: |
          echo "PWD: $(pwd)"
          echo "Workspace content (root):"
          ls -la
          echo "Git-tracked files (first 200):"
          git ls-files | sed -n '1,200p'

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Verify Python & pip
        run: |
          python -V
          pip -V

      - name: Install dependencies (backend)
        run: |
          if [ ! -f backend/requirements.txt ]; then
            echo "ERROR: backend/requirements.txt NO existe" >&2
            exit 1
          fi
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
          pip install pytest

      - name: Lint (basic syntax check)
        run: |
          PY_FILES="$(git ls-files '*.py' || true)"
          if [ -n "$PY_FILES" ]; then
            echo "Linting these files:"
            echo "$PY_FILES"
            python -m py_compile $PY_FILES || true
          else
            echo "No hay archivos .py aún, omitimos lint"
          fi

      - name: Run tests (pytest)
        run: |
          if [ -d backend/tests ]; then
            pytest -q backend/tests || true
          else
            echo "No hay carpeta backend/tests, omitimos tests"
          fi
